---

- name: Include provider get default tasks
  include_tasks: "get_{{ cloud_vpn_responder_provider }}_defaults.yaml"

- block:
    - name: Get VPC facts
      os_networks_facts:
        cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
        name: "{{ cloud_vpn_responder_vpc_id }}"

    - name: Set responder subnet ID
      set_fact:
        cloud_vpn_responder_subnet_id: "{{ openstack_networks[0]['subnets'][0] }}"

    - name: Generate responder provision template
      template:
        src: provisioners/openstack_instance/responder/provision_in_existing_vpc.j2
        dest: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"
  when: cloud_vpn_responder_vpc_id is defined

- name: Generate responder provision template
  template:
    src: provisioners/openstack_instance/responder/provision.j2
    dest: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"
  when: cloud_vpn_responder_vpc_id is not defined

- name: Create responder stack
  os_stack:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    name: "{{ cloud_vpn_name }}-responder-stack"
    template: "/tmp/{{ cloud_vpn_name }}-responder-provision.template"

- name: Get instance facts
  os_server_facts:
    cloud: "{{ cloud_vpn_responder_openstack_cloud }}"
    server: "{{ cloud_vpn_name }}-responder-instance"
  register: out

- name: Set responder IP fact
  set_fact:
    cloud_vpn_responder_public_ip: "{{ openstack_servers[0]['interface_ip'] }}"
